name: Windows Build and Inno Setup

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -U pip imageio
        python -m pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"

    - name: Build with Nuitka
      run: |
        python -m nuitka --show-progress --standalone --enable-plugin=pyside6 --plugin-enable=numpy --enable-plugin=tensorflow --enable-plugin=matplotlib --windows-icon-from-ico=gui/icons/sherloq_alpha.png --output-dir=build gui/sherloq.py

    - name: Copy necessary files to build directory
      run: |
        xcopy /s /y icons build\
        xcopy /s /y ssimulacra build\
        xcopy /s /y noiseprint build\
        xcopy /s /y pyexiftool build\
        xcopy /s /y butteraugli build\

    - name: Package into Zip
      run: |
        Compress-Archive -Path build\* -DestinationPath sherloq-package.zip

    - name: Compile Inno Setup Script
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: sherloq_installer_script.iss
        options: /DMyAppIcon=gui/icons/sherloq_alpha.png 
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sherloq-package
        path: sherloq-package.zip
        retention-days: 1
